hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task:
    - experiment.seed=1,2,3,4,5,6,7,8,9,10
  job:
    name: train
    chdir: null
    override_dirname: experiment.seed=1,2,3,4,5,6,7,8,9,10
    id: ???
    num: ???
    config_name: base
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.3.2
    version_base: '1.3'
    cwd: /Users/ray/Downloads/Documents/Developer/Model/CLLM-DH
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /Users/ray/Downloads/Documents/Developer/Model/CLLM-DH/configs
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
experiment:
  name: gan_vs_gbm_deep_hedging
  seed: 42
  device: cuda
data:
  source: synthetic
  path: data/raw/sp500.csv
  start_date: '2015-01-01'
  end_date: '2025-01-01'
  ticker: SPY
  interval: 1d
  resample_freq: 8T
  splits:
    train:
    - start: '2015-01-01'
      end: '2017-12-31'
    - start: '2019-02-01'
      end: '2019-11-30'
    - start: '2021-01-01'
      end: '2022-12-31'
    valid:
    - start: '2018-01-01'
      end: '2018-06-30'
    - start: '2020-06-01'
      end: '2020-12-31'
    test:
    - name: covid19
      start: '2020-02-15'
      end: '2020-04-30'
    - name: volmageddon
      start: '2018-01-15'
      end: '2018-02-28'
    - name: qt18
      start: '2018-10-01'
      end: '2018-12-31'
    - name: svb23
      start: '2023-03-01'
      end: '2023-03-31'
    - name: hikes22
      start: '2022-06-01'
      end: '2022-07-31'
model:
  gan:
    input_dim: 10
    hidden_dim: 128
    sequence_length: 60
    num_layers: 2
    dropout: 0.2
    latent_dim: 32
    adv_lambda: 0.7
    lr_generator: 0.0002
    lr_discriminator: 0.0002
  hedger:
    state_dim: 10
    hidden_dim: 128
    sequence_length: 60
    num_layers: 2
    dropout: 0.2
    lr: 0.0003
    entropy_coef: 0.01
training:
  gan:
    num_epochs: 100
    batch_size: 64
    cvar_alpha: 0.95
  hedger:
    num_episodes: 1000
    lr: 0.001
    transaction_cost: 0.0001
environment:
  initial_capital: 100000
  transaction_cost: 0.0001
  episode_length: 60
  position_scale: 1000
risk:
  cvar_confidence: 0.95
  risk_free_rate: 0.02
  volatility_window: 20
logging:
  log_level: INFO
  wandb_project: deep_hedging
  log_dir: runs
  save_models: true
  plot_results: true
  plot_dpi: 300
deterministic:
  torch_seed: 42
  numpy_seed: 42
  python_seed: 42
  deterministic_mode: true
  cuda_deterministic: true
  cuda_benchmark: false
